### ISSUE TITLE
Gap-filled_% of the SWdown variable in the Ozfulx  sites

### ISSUE THREAD

**Issue by Mbnl1197** [aukkola/PLUMBER2#3]
Hello,Anna!
I have a little doubt about the Gap-filled_% of variable SWdown in the Ozfulx sites.
I have noticed that its value is relatively high in many sites. For example, site AU-How and site AU-Cpr are 40.8 and 49.4, respectively.
Why are their values relatively high, and are the data from these sites reliable?
Can you help me dispel this question that bothers me?
THANKS！
Jiahao

**Comment by aukkola** [comment]
Hi Jiahoa,

This is because the original OzFlux data has been processed a little differently to, for example, Fluxnet2015. In the original dataset, there are non-physical values for some meteorological variables but the creators of the dataset decided to keep these in order to not bias the overall data. In the case of SWdown, these non-physical data include negative values of SWdown. In processing our data, we have set all negative values to zero as these would cause issues with model simulations. In doing so, these time steps were labelled as "gap-filled" as we have modified the original data. We have had to apply similar corrections to other meteorological variables. In the case of Howard Springs for example, there are a lot of negative SWdown values so the percentage of "gap-filled" data is high. (You can identify the time steps that have been corrected from a qc value of 101). Most of these time steps were observed data in the original dataset so the data is mostly reliable.

Thanks,
Anna

**Comment by Mbnl1197** [comment]
> 
Hi, Anna,

I appreciate your reply.
I have a clear understanding of this question through your answer.

Thanks,
Jiahao
