### ISSUE TITLE
Ground heat flux and energy closure of CN-Du2

### ISSUE THREAD

**Issue by Mbnl1197** [aukkola/PLUMBER2#5]
Hello,Anna!

I found that although there is a variable of ground heat flux in CN-Du2, its values are all Nan. At the same time, this site has carried on the energy closure processing. However, according to the energy closure process, there is no way to deal with energy closure without G observation. 
I want to know what might have happened  to help me use the data.

Thanks!
Jiahao

**Comment by aukkola** [comment]
Hi Jiahao,

Ah that's because we use the full time series to do the energy balance correction. That is, all the time steps that are available in the original FLUXNET2015 dataset. After the EB correction, we quality control the data further and at some sites remove years from the dataset (due to bad quality met data). At CN-Du2, there are ground heat flux values available during the first year but we've removed this year from the final dataset due to our quality control. (see the panel for Qg in the figure below). Hence it appears in the final files that no Qg is available, sorry for the confusion.

Thanks,
Anna

![CN-Du2_timeseries_plot](https://user-images.githubusercontent.com/19399657/199981945-9e94aaf5-acd5-4b20-a636-8106080fd724.png)

**Comment by Mbnl1197** [comment]
Hi, Anna,

Thank you for your prompt reply.
I'm sorry I didn't notice that. I already understand after your explanation.

Thanks,
Jiahao
